// Here is a list of the people on our team.

// 1. What are the five most popular first names?

// 2. What are the five most popular last names?

// 3. Which "magic" names occur as both first and last names?

// 4. Which "magic" people have a first name that is someone's last name, and a last name that is someone's first name?

// 5. People are in a group if their names are connected in some way. For example, Landin King, Roger King, and Roger Geng are in a group of 3 people. Print the number of groups of each size.

// 6. Do the results change if you add your name to the list?

// Diagram: https://andrewzc.net/interviews/names.pdf

import Foundation

let data = [
  "Aaron Mendoza",
  "Aaron Wilson",
  "Abhishek Maheshwari",
  "Abhishek Sarihan",
  "Abhishek Tiwari",
  "Abigail Watson",
  "Adam Beckerman",
  "Adam Ochayon",
  "Adam Perea-Kane",
  "Adithya Ravikumar",
  "Aditya Mittal",
  "Aditya Risbud",
  "Alan Hu",
  "Alan Wang",
  "Alex Gates-Shannon",
  "Alex McKinney",
  "Alex Meyers",
  "Alex Nelson",
  "Alex Stern",
  "Alexander Zaman",
  "Alexandre Petcherski",
  "Alexei Isac",
  "Alexis Moody",
  "Ali Weaver",
  "Alice Mariano",
  "Alice Yoon",
  "Alissa Mittelberg",
  "Allen Garzone",
  "Allison Moore",
  "Allison Ng",
  "Amit Sazawal",
  "Amit Wadhera",
  "Amy Takata",
  "Amy Wiggins",
  "Amy Zheng",
  "Andrea Dudla",
  "Andrew Garrett",
  "Andrew Lo",
  "Andrew Sheh",
  "Andrew Whittaker",
  "Andrew Zamler-Carhart",
  "Andrey Patrov",
  "Andris Zvargulis",
  "Angel Dionisio",
  "Angelina Lam",
  "Ankit Yadav",
  "Anna Avrekh",
  "Anna Lee",
  "Annie Chen",
  "Anthony Escamilla",
  "Anthony Gonzales",
  "Anya Tran",
  "Aparna Parlapalli",
  "Aren Jidarian",
  "Armapreet Suri",
  "Arun Christopher",
  "Arun Mikkilineni",
  "Arup Das",
  "Arup Sarkar",
  "Ashley Murphy",
  "Ashrit Kamireddi",
  "Ashton Alexander",
  "Avraham Blaut",
  "Azfar Aziz",
  "Balsaheb Dabhade",
  "Bart Karmilowicz",
  "Basia Mucha",
  "Bastien Falcou",
  "Beatrice Mendoza",
  "Ben Griffin",
  "Ben Hoyt",
  "Ben Huang",
  "Bernie Mulligan",
  "Bharath Swamy",
  "Bilal Siddiqui",
  "Björn Skoglund",
  "Bo Huang",
  "Bobby Singh",
  "Boris Veltman",
  "Brandon Kessler",
  "Brendan Stafford",
  "Brian Ha",
  "Brian Renzenbrink",
  "Brian Ross",
  "Brian To",
  "Brittany Chait",
  "Cade Cairns",
  "Caitlyn Hampton",
  "Calvin Lee",
  "Cameron Waeland",
  "Carina Ursu",
  "Catarina Tsang",
  "Cevon Carver",
  "Chad Cohen",
  "Chanel Weathers",
  "Chang Yu",
  "Charles Bai",
  "Charles Bentivenga",
  "Charles Bunton",
  "Charles Dannaker",
  "Charvi Agarwal",
  "Chen Huang",
  "Chester Millisock",
  "Chi Ho",
  "Chiyi Wang",
  "Chloe Drew",
  "Chloe Powell",
  "Chong Qiu",
  "Chris Bejnar",
  "Chris Ewen",
  "Chris Lee",
  "Chris Seltzer",
  "Chrissy Oliver",
  "Christa Gerard",
  "Christian Lusetti",
  "Christina Allen",
  "Christopher Bejnar",
  "Cindy Zhang",
  "Claire Cipriani",
  "Claudia Wen",
  "Connor Scott",
  "Cory Perkins",
  "Craig Brookes",
  "Dajia Bao",
  "Daljeet Kukreja",
  "Dan Clark",
  "Dan Edenhofer",
  "Dan McClure",
  "Dan Raykhlin",
  "Dana Bruschi",
  "Dani Dugan",
  "Dani Medina",
  "Daniel Epstein",
  "Daniel Han",
  "Daniel Sanchez",
  "Daniel Straus",
  "Danielle Shwed",
  "Danny Lynch",
  "Danny Somekh",
  "Danylo Shpit",
  "Dave Barth",
  "Dave DeSandro",
  "David Mulatti",
  "David Shure",
  "David Szczepanski",
  "Dean Hunt",
  "Derrick Nguyen",
  "Dexter Callender",
  "Didi Medina",
  "Dilip Gajendran",
  "Ding Zhou",
  "DiXi Qiao",
  "Dixi Qiao",
  "Djam Saidmuradov",
  "Don Hoang",
  "Donald Gray",
  "Dorian Manning",
  "Drew Libin",
  "Eda Kaplan",
  "Edward Hu",
  "Ellie Trulinger",
  "Emily Ho",
  "Emma Magaw",
  "Eric Beltran",
  "Erin Thwaites",
  "Etai Plushnick",
  "Ethan Fuld",
  "Evan Arbeitman",
  "Evan Compton",
  "Evan Johnson",
  "Evgeny Semenov",
  "Eyal Maaravi",
  "Fabian Moya",
  "Fangbo Yang",
  "Fangzhou Lan",
  "Fangzhou Yan",
  "Felix Wei",
  "Feng Tang",
  "Foster Provost",
  "Freddy Munoz",
  "Fu Zhou",
  "Gabor Varga",
  "Gautam Narula",
  "Geet Bhanawat",
  "George Markantonis",
  "Grant Harper",
  "Greg Mushen",
  "Greg Scott",
  "Griffin Jones",
  "Guanghao Ding",
  "Guillermo Ortiz",
  "Hadar Yacobovitz",
  "Haiyang Si",
  "Hallie Sullivan",
  "Han Chae",
  "Hao Jiang",
  "Harel Williams",
  "Harry Niu",
  "HeeMin Kim",
  "Henry Guo",
  "Henry Lee",
  "Henry Warren",
  "Henry Xu",
  "Henry Zhao",
  "Herson Castillo",
  "Hezhi Wang",
  "Himanshi Nagpal",
  "Hiram Moncivais",
  "Hongwei Wang",
  "Hu Zhou",
  "Huaxia Zhao",
  "Ian Cohan-Shapiro",
  "Ilya Timofeyev",
  "Jack Amadeo",
  "Jack Murphy",
  "Jack Richards",
  "Jackie Lynch",
  "Jackson Cheek",
  "Jaclyn Verga",
  "Jacob Bisnett",
  "Jacob Patterson",
  "Jamal Carvalho",
  "James Chen",
  "James Manlapid",
  "Jane Calvin",
  "Jane Park",
  "Jane Wang",
  "Jared Lindauer",
  "Jason Byck",
  "Jason LaCarrubba",
  "Jason Pao",
  "Jason Reid",
  "Jason Walker-Yung",
  "Jean Barmash",
  "Jean Castillo",
  "Jeffrey Cole",
  "Jeffrey Hunt",
  "Jeffrey Tierney",
  "Jeffrey Tuarez",
  "Jen Vandagriff",
  "Jen Yuan",
  "Jennifer Cen",
  "Jennifer Wang",
  "Jenny Koren",
  "Jeremy Huang",
  "Jeremy Schwartz",
  "Jessica Solka",
  "Jessie Gong",
  "Jesus Zalapa",
  "Jiazhi Ou",
  "Jim Li",
  "Jim Zhan",
  "Jinbo Zhou",
  "Jiqun Qi",
  "Joanne Juan",
  "Joe Woodard",
  "John Gerhardt",
  "John Gold",
  "John Simon",
  "Johnny Zhou",
  "Jon Fu",
  "Jonathan Word",
  "Jonny Mooneyham",
  "Jose Salamone",
  "Joseph Galindo",
  "Joseph Schmitt",
  "Joseph Sirosh",
  "Joseph Sortland",
  "Josh Attenberg",
  "Josh Burton",
  "Josh Kegley",
  "Josh Nili",
  "Josh Stern",
  "Juan Ayala",
  "Julia Poladsky",
  "Julian Kim",
  "Julio Dionisio",
  "Jun Du",
  "Junqi Liao",
  "Junyu Tian",
  "Justin Binns",
  "Justin Poston",
  "Kai Zhong",
  "Kaili Xu",
  "Kamal Behara",
  "Karan Nischol",
  "Kari Oliveira",
  "Karl Jin",
  "Karthik Sangam",
  "Kashmira Deshpande",
  "Kashyap Dixit",
  "Kate Dixon",
  "Kate McNulty",
  "Kathryn Hart",
  "Katy Hockerman",
  "Kayla Farrell",
  "Kayoung Lee",
  "Keith Rose",
  "Kelly Reed",
  "Kenneth Bergquist",
  "Kenny Hom",
  "Kensey Olsen",
  "Keren Katz",
  "Kevin Baijnath",
  "Kevin Li",
  "Kevin Liu",
  "Kevin Mitchell",
  "Kevin Reid",
  "Kevin Wong",
  "Khadija Ali",
  "Kim Nguyen",
  "Kiran Akadas",
  "Kiron Sukesan",
  "Ksenia Coulter",
  "Kyle Rocco",
  "Kyler Cameron",
  "Lan Jiang",
  "Landin King",
  "Laura Crossin",
  "Laura Gagliano",
  "Lauren Elliott",
  "Lauren Jones",
  "Lauren Wood",
  "Lawrence Manfredi",
  "Lee Pollard",
  "Leilah Williams",
  "Lena Johnson",
  "Leo Yu",
  "Levi Meyer",
  "Lexi Hart",
  "Lihui Cai",
  "Lilly Ju",
  "Limian Wang",
  "Lindsay Owen",
  "Ling Zhang",
  "Lucas Lain",
  "Lucas Reis",
  "Lucy Zhong",
  "Luigi Kapaj",
  "Luke Downey",
  "Luran He",
  "Lycurgo Vidalakis",
  "Manimaran Parimegazhagan",
  "Manish Dalmia",
  "Manoj Sarwa",
  "Manuela Montagana",
  "Margie Ruparel",
  "Mark Humphrey",
  "Mark Mayer",
  "Martyna Michalska",
  "Mary Rabin",
  "Masha Malygina",
  "Matt Fortuna",
  "Matt Garza",
  "Matt Spangler",
  "Matthew Reitz",
  "Matthew Schoen",
  "Max Spinner",
  "Megan Clegg",
  "Melissa Delgado",
  "Michael Chen",
  "Michael Ewen",
  "Michael Hansen",
  "Michael Lefco",
  "Michael Marion",
  "Michael Niday",
  "Michael Quinn",
  "Michael Walters",
  "Michael Wang",
  "Michaela Keady",
  "Michele Manfredi",
  "Michelle Choi",
  "Michelle Johnson",
  "Michelle Yoon",
  "Min Zhang",
  "Mingbo Xu",
  "Miranda Ashley",
  "Mitchell Candreva",
  "Monica Lee",
  "Moya Farvis",
  "Murtaza Icecreamwala",
  "Naader Khan",
  "Nabarun Mondal",
  "Naomi Robert",
  "Nate Rentmeester",
  "Nathan Miranda",
  "Nathan Wang",
  "Nathaniel Brakeley",
  "Nathaniel Morihara",
  "Nicole Coddington",
  "Nicole Reinhardsen",
  "Nicole Yoblick",
  "Nikin Raghav",
  "Niko Mavrakis",
  "Nina Walker",
  "Ning Cui",
  "Noah Schwartz",
  "Octavio Roscioli",
  "Oliver Castillo",
  "Oliver Scott",
  "Ori Allon",
  "Ori Damary",
  "Osman Ozdemir",
  "Owen Charles",
  "Ozgur Akduran",
  "Pablo Mata",
  "Panos Ipeirotis",
  "Paola Justiniano",
  "Parth Patel",
  "Paul Brown",
  "Perry Yee",
  "Peter Liang",
  "Peter Liu",
  "Peter Ryan",
  "Peter Ta",
  "Poorva Warghade",
  "Prakrati Dangarh",
  "Preetpal Phandar",
  "Priyanka Khire",
  "Rachel Spikula",
  "Raghav Garg",
  "Raghav Lohit",
  "Raghav Sachdev",
  "Rahul Marepalli",
  "Rahul Ratnakar",
  "Rahul Singh",
  "Raju Matta",
  "Ran Ding",
  "Ran Ju",
  "Raquel Bujans",
  "Ray Bueno",
  "Raymond Leung",
  "Raymond Wang",
  "Renato Gamboa",
  "Revathi Kandoji",
  "Rex Zhang",
  "Rich Pean",
  "Rich Simon",
  "Rob Miller",
  "Robert Chen",
  "Robert Gray",
  "Robert Reffkin",
  "Rocky Chen",
  "Roger Geng",
  "Roger King",
  "Rohit Khanwani",
  "Rohit Kommareddy",
  "Rolando Penate",
  "Roman Blum",
  "Roman Valiouline",
  "Rong Chen",
  "Ross Bierbryer",
  "Roy Yu",
  "Ruchira Agrawal",
  "Rushabh Gaherwar",
  "Russell Kaehler",
  "Russell Stephens",
  "Ruth Reffkin",
  "Ryan D'souza",
  "Ryan Houston",
  "Sagar Vora",
  "Saket Joshi",
  "Saket Kumar",
  "Sam Grone",
  "Sam Lynch",
  "Sam Rowland",
  "Sam Sandoval",
  "Sam Stevens",
  "Sammy Shaar",
  "Samuel Rispaud",
  "Samuel Weiss",
  "Samwise Rowe",
  "Sana Sheikh",
  "Sandeep Reddy",
  "Sandesh Baliga",
  "Sangeeta Kilkarni",
  "Sarah Ahmed",
  "Sarah Fisher",
  "Sarah Han",
  "Sarah Jang",
  "Sarath Mantrala",
  "Sarita Goswami",
  "Sarthak Baiswar",
  "Satwik Seshasai",
  "Saurabh Kumar",
  "Saurabh Shah",
  "Savanna Butterworth",
  "Savio Fernandes",
  "Scott Bierbryer",
  "Scott Block",
  "Scott Roepnack",
  "Sean Hunt",
  "Sean Fitzell",
  "Sean Hallahan",
  "Sean Wheeler",
  "Shah Noor",
  "Shannon O’Donnell",
  "Shannon Sullivan",
  "Sharon Kapitula",
  "Sharon Kim",
  "Shauna Suthersan",
  "Shayaan Ali",
  "Shean Kim",
  "Shelley Zhong",
  "Shenzhi Li",
  "Shiloh Stuart",
  "Shiovawn Manning",
  "Shirley Zhang",
  "Shiyang Fei",
  "Shiyuan Wang",
  "Shujia Liu",
  "Shuky Meyer",
  "Sid Singh",
  "Siddharth Sarasvati",
  "Siddharth Singh",
  "Sierra Swaby",
  "Simon Thomas",
  "Siyuan Zhu",
  "Smriti Mehra",
  "Sohom Bhattacharya",
  "Sophia Fleming-Benite",
  "Sophia Hu",
  "Sourav Dutta",
  "Spencer Duff",
  "Stefanie Wiener",
  "Stephanie Trimboli",
  "Stephen Harrison",
  "Stephen Spyropoulos",
  "Stephen Stoll",
  "Steve Zhu",
  "Steven Cheshire",
  "Sudip Biswas",
  "Sujit Poudel",
  "Suvayan Roy",
  "Tal Amitai",
  "Tal Netanyahu",
  "Tania Goswami",
  "Tao Xie",
  "Terry Zheng",
  "Theodore Rose",
  "Theresa Swift",
  "Thomas Cardwell",
  "Thomas Hallock",
  "Thomas Tran",
  "Timothee Roussilhe",
  "Timothy Knox",
  "Tingzhen Du",
  "Todd Parmley",
  "Tong Li",
  "Tony Chung",
  "Tracy Miller",
  "Travis Van Belle",
  "Trevor Burnham",
  "Trish Jin",
  "Tristan Brandon",
  "Troy Crosby",
  "Tuan-Chun Chen",
  "Tushar Kathuria",
  "Ugo DiGirolamo",
  "Upen Kaki",
  "Veeru Namuduri",
  "Veronica Ray",
  "Vianna Vuong",
  "Victor Zhu",
  "Vin Halbwachs",
  "Vincent Callahan",
  "Vincent Vuong",
  "Vivek Viswanathan",
  "Vivian Wong",
  "Warren Miller",
  "Wei Su",
  "Wei Wang",
  "Weikun Tang",
  "Wen Ye",
  "Wes Billman",
  "Wes Vial",
  "Wes Zeng",
  "Will Decker",
  "Will Yang",
  "Will Zhao",
  "William Bradley",
  "William Horton",
  "William Macarthur-Stanham",
  "Willy Wang",
  "Xi Lian",
  "Xianbin Wu",
  "Xiao Cui",
  "Xiao Fu",
  "Xiaofan Tong",
  "Xiaoguang Li",
  "Xin Liu",
  "Xinxin Pan",
  "Yang Zhang",
  "Yao Ding",
  "Yaron Schoen",
  "Yen Chen",
  "Yi Chen",
  "Yi Wen",
  "Yilei Mou",
  "Ying Chen",
  "Yongjian Bi",
  "Yuan Guo",
  "Yue Bi",
  "Yue Zhang",
  "Yuvraj Vedvyas",
  "Yuwei Hu",
  "Yvonne Wang",
  "Zach Ozer",
  "Zach Plata",
  "Zack Gao",
  "Zhao Song",
  "Zhenfei Tai",
  "Zheng Hu",
  "Zhifeng Shi",
  "Zhixiang Ren",
  "Zhongxia Zhou",
  "Zhouqian Ma",
  "Zhuoyuan Zhang",
  "Zi Lian",
  "Zihang Yin",
  "Zikang Yao",
  "Zoey Sun",
  "Zvi Band"
]

class Name {
  static var nameIndex = [String:Name]()

  var name: String
  var firsts = [Person]()
  var lasts = [Person]()
  var visited = false

  init(name: String) {
    self.name = name
  }

  static func getName(_ value: String) -> Name {
    if let name = nameIndex[value] {
      return name
    } else {
      let name = Name(name:value)
      nameIndex[value] = name
      return name
    }
  }

  func firstNames() -> String {
    return lasts.map {$0.first.name}.joined(separator: ", ")
  }

  func lastNames() -> String {
    return firsts.map {$0.last.name}.joined(separator: ", ")
  }

  func isMagic() -> Bool {
    return firsts.count > 0 && lasts.count > 0
  }

  func totalCount() -> Int {
    return firsts.count + lasts.count
  }

  func countPeople() -> Int {
    if visited {
      return 0
    }
    visited = true
    return (firsts + lasts).reduce(0) { $0 + $1.countNames() }
  }
}

class Person {
  static var people = [Person]()

  var first: Name
  var last: Name
  var visited = false

  init(first: Name, last: Name) {
    self.first = first
    self.last = last
  }

  static func loadPeople(_ data: [String]) {
    data.forEach {
      let strings = $0.components(separatedBy: " ")
      let first = Name.getName(strings[0])
      let last = Name.getName(strings[1])
      let person = Person(first:first, last:last)
      first.firsts.append(person)
      last.lasts.append(person)
      people.append(person)
    }
  }

  func isMagic() -> Bool {
    return first.lasts.count > 0 && last.firsts.count > 0
  }

  func countNames() -> Int {
    if visited {
      return 0
    }
    visited = true
    return 1 + first.countPeople() + last.countPeople()
  }
}

Person.loadPeople(data)

var names = Array(Name.nameIndex.values)

print("Top first names:")
names
  .filter { _ in true } // TODO: find top first names
  .sorted { $0.firsts.count > $1.firsts.count }[0...4]
  .forEach { print($0.name, "-", $0.lastNames()) }

print("\nTop last names:")
names
  .filter { _ in true } // TODO: find top last names
  .sorted { $0.lasts.count > $1.lasts.count }[0...4]
  .forEach { print($0.name, "-", $0.firstNames()) }

print("\nMagic names:")
names
  .filter { _ in true } // TODO: find magic names
  .filter { $0.isMagic() }
  .sorted { $0.totalCount() > $1.totalCount() }
  .forEach { print($0.name, "-", $0.firstNames(), "/", $0.lastNames()) }

print("\nMagic people:")
Person.people
  .filter { _ in true } // TODO: find magic people
  .filter { $0.isMagic() }
  .forEach { print($0.first.name, $0.last.name) }

print("\nCluster sizes:")
var clusterSizes = [Int:Int]() // TODO: update clusterSizes
names.forEach { name in
  if !name.visited {
    clusterSizes[name.countPeople(), default: 0] += 1
  }
}

Array(clusterSizes.keys)
  .sorted()
  .forEach { print("\($0): \(clusterSizes[$0]!)") }
